export const GOT_TODOS = 'GOT-TODOS';
export const NEW_TODO_ADDED = 'NEW-TODO-ADDED';
export const TODO_UPDATED = 'TODO-UPDATED';
export const TODO_DELETED = 'TODO-DELETED';
export const DONE_WERE_CLEARED = 'DONE-WERE-CLEARED';
export const CHANGE_IS_CONFIRMED_ALL_STATUS_CHANGED =
  'CHANGE-IS-CONFIRMED-ALL-STATUS-CHANGED';
